apiVersion: v2
name: service-chart
description: A Helm chart for Kubernetes

type: application
version: 0.0.1
appVersion: v1

dependencies:
  - name: postgresql
    version: 8.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - services-database
