replicaCount: 2

image:
  repository: fanyshu/otus-arch-hw:v9

service:
  type: NodePort
  port: 8000

ingress:
  enabled: true
  hosts:
    - host: otus-hw.test
      paths: ["/otusapp"]

metrics:
  serviceMonitor:
    enabled: true

postgresql:
  enabled: true
  postgresqlUsername: "postgres"
  postgresqlPassword: "password"
  postgresqlDatabase: "postgres_homework"
  service:
    port: "5432"