version: "3.1"
services:
  redis:
    image: "redis:alpine"
    entrypoint: redis-server --appendonly yes
    restart: always
    ports:
     - "6379:6379"
    volumes:
     - ./redis-data:/var/lib/redis

  homework_db:
    container_name: homework_db
    image: postgres
    tty: true
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: arch_homework
      POSTGRES_USER: arch_homework
      POSTGRES_PASSWORD: arch_homework
    volumes:
      - ./database:/var/lib/postgresql/data
