  
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: myapp-api
spec:
  rules:
  - host: otus.homework
    http:
      paths:
      - backend:
          serviceName: myapp-api
          servicePort: {{ .Values.service.port }}
        path: /signin
      - backend:
          serviceName: myapp-api
          servicePort: {{ .Values.service.port }}
        path: /signup
      - backend:
          serviceName: myapp-api
          servicePort: {{ .Values.service.port }}
        path: /logout
      - backend:
          serviceName: myapp-api
          servicePort: {{ .Values.service.port }}
        path: /user
      - backend:
          serviceName: myapp-api
          servicePort: {{ .Values.service.port }}
        path: /auth