apiVersion: v1
kind: ConfigMap
metadata:
  name: app-api-config
data:
  HW_HTTP_BIND_PORT: "8000"
  POSTGRES_DB: "postgres_homework"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-api-secret
type: Opaque
data:
  HW_DBSN: aG9zdD1teWFwcC1hcGktcG9zdGdyZXNxbCBwb3J0PTU0MzIgdXNlcj1wb3N0Z3JlcyBwYXNzd29yZD1wYXNzd29yZCBkYm5hbWU9cG9zdGdyZXNfaG9tZXdvcmsgc3NsbW9kZT1kaXNhYmxlIGNvbm5lY3RfdGltZW91dD01IGJpbmFyeV9wYXJhbWV0ZXJzPXllcw==
  DB_URI: cG9zdGdyZXNxbDovL215YXBwLWFwaS1wb3N0Z3Jlc3FsL3Bvc3RncmVzX2hvbWV3b3JrP3VzZXI9cG9zdGdyZXMmcGFzc3dvcmQ9cGFzc3dvcmQ=
  POSTGRES_PASSWORD: cGFzc3dvcmQ=