# apiVersion: networking.k8s.io/v1beta1
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myapp-api
spec:
  rules:
  - host: arch.homework
    http:
      paths:
      - backend:
          serviceName: myapp
          servicePort: {{ .Values.service.port }}
        path: /products
      - backend:
          serviceName: myapp
          servicePort: {{ .Values.service.port }}
        path: /health/check
