  
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: myapp-api
spec:
  rules:
  - host: arch.homework
    http:
      paths:
      - backend:
          serviceName: myapp-api
          servicePort: {{ .Values.service.port }}
        path: /products