swagger: '2.0'
info:
  title: Otus-Arch-homework
  description: Otus architecture homework 3
  version: 1.0.0
paths:
  /users/me:
    get:
      summary: Get user info
      operationId: GetUserInfo
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - $ref: '#/parameters/XUserEmail'
        - $ref: '#/parameters/XUserFirstName'
        - $ref: '#/parameters/XUserLastName'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/UserProperties'

parameters:
  XUserEmail:
    name: X-User-Email
    in: header
    type: string
    required: true
  XUserFirstName:
    name: X-User-First-Name
    in: header
    type: string
    required: true
  XUserLastName:
    name: X-User-Last-Name
    in: header
    type: string
    required: true

definitions:
  UserProperties:
    type: object
    description: User info
    required:
      - Email
      - FirstName
      - LastName
    properties:
      Email:
        type: string
        minLength: 1
        description: User email address
      FirstName:
        type: string
        description: User first name
      LastName:
        type: string
        description: User last name

  FailResponse:
    description: Error response
    type: object
    required:
      - error
    properties:
      error:
        type: string
        minLength: 1
        description: Error message