apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: myapp
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://myapp-api.default.svc.cluster.local:8000/auth"
    nginx.ingress.kubernetes.io/auth-signin: "http://$host/signin"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-User-Email,X-User-First-Name,X-User-Last-Name"
spec:
  rules:
  - host: otus.homework
    http:
      paths:
      - backend:
          serviceName: myapp
          servicePort: {{ .Values.service.port }}
        path: /users/me