{
 "title": "Latency",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Nginx-ingress latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, exported_endpoint) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le, exported_endpoint) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le, exported_endpoint) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Nginx-ingress RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method) (rate(nginx_ingress_controller_request_duration_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Nginx-ingress Error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[1m]))"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_endpoint) (rate(app_request_count{handler_name=\"/users\",method_name=\"GET\"}[1m]))",
     "legendFormat": "RPS /users GET"
    },
    {
     "expr": "sum by (exported_endpoint) (rate(app_request_count{handler_name=\"/users\",method_name=\"POST\"}[1m]))",
     "legendFormat": "RPS /users POST"
    },
    {
     "expr": "sum by (exported_endpoint) (rate(app_request_count{handler_name=\"/users\",method_name=\"PUT\"}[1m]))",
     "legendFormat": "RPS /users PUT"
    },
    {
     "expr": "sum by (exported_endpoint) (rate(app_request_count{handler_name=\"/users\",method_name=\"DELETE\"}[1m]))",
     "legendFormat": "RPS /users DELETE"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, exported_endpoint) (rate(app_request_duration_time_bucket{handler_name=\"/users\",method_name=\"GET\"}[1m])))",
     "legendFormat": "/users GET 0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le, exported_endpoint) (rate(app_request_duration_time_bucket{handler_name=\"/users\",method_name=\"GET\"}[1m])))",
     "legendFormat": "/users GET 0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le, exported_endpoint) (rate(app_request_duration_time_bucket{handler_name=\"/users\",method_name=\"GET\"}[1m])))",
     "legendFormat": "/users GET 0.99"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le, exported_endpoint) (rate(app_request_duration_time_bucket{handler_name=\"/users\",method_name=\"POST\"}[1m])))",
     "legendFormat": "/users POST 0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le, exported_endpoint) (rate(app_request_duration_time_bucket{handler_name=\"/users\",method_name=\"POST\"}[1m])))",
     "legendFormat": "/users POST 0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le, exported_endpoint) (rate(app_request_duration_time_bucket{handler_name=\"/users\",method_name=\"POST\"}[1m])))",
     "legendFormat": "/users POST 0.99"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le, exported_endpoint) (rate(app_request_duration_time_bucket{handler_name=\"/users\",method_name=\"PUT\"}[1m])))",
     "legendFormat": "/users PUT 0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le, exported_endpoint) (rate(app_request_duration_time_bucket{handler_name=\"/users\",method_name=\"PUT\"}[1m])))",
     "legendFormat": "/users PUT 0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le, exported_endpoint) (rate(app_request_duration_time_bucket{handler_name=\"/users\",method_name=\"PUT\"}[1m])))",
     "legendFormat": "/users PUT 0.99"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le, exported_endpoint) (rate(app_request_duration_time_bucket{handler_name=\"/users\",method_name=\"DELETE\"}[1m])))",
     "legendFormat": "/users DELETE 0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le, exported_endpoint) (rate(app_request_duration_time_bucket{handler_name=\"/users\",method_name=\"DELETE\"}[1m])))",
     "legendFormat": "/users DELETE 0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le, exported_endpoint) (rate(app_request_duration_time_bucket{handler_name=\"/users\",method_name=\"DELETE\"}[1m])))",
     "legendFormat": "/users DELETE 0.99"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{instance=\"172.17.0.12:8000\",pod=\"myapp-service-chart-84c596cb6c-866wg\"}",
     "legendFormat": "myapp-service-chart-84c596cb6c-866wg"
    },
    {
     "expr": "go_goroutines{instance=\"172.17.0.12:8000\",pod=\"myapp-service-chart-7b5d759fd4-rfwpl\"}",
     "legendFormat": "myapp-service-chart-7b5d759fd4-rfwpl"
    }
   ]
  },
  {
   "title": "Errors rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(app_request_count{status_code=\"500\"})",
     "legendFormat": "/users"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=\"myapp-service-chart-7b5d759fd4-rfwpl\"}[5m]))",
     "legendFormat": "POD myapp-service-chart-7b5d759fd4-rfwpl"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=\"myapp-service-chart-84c596cb6c-866wg\"}[5m]))",
     "legendFormat": "POD myapp-service-chart-84c596cb6c-866wg"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{instance=\"172.17.0.12:8000\",pod=\"myapp-service-chart-84c596cb6c-866wg\"}",
     "legendFormat": "myapp-service-chart-84c596cb6c-866wg"
    },
    {
     "expr": "go_memstats_alloc_bytes{instance=\"172.17.0.12:8000\",pod=\"myapp-service-chart-7b5d759fd4-rfwpl\"}",
     "legendFormat": "myapp-service-chart-7b5d759fd4-rfwpl"
    }
   ]
  }
 ]
}