apiVersion: batch/v1
kind: Job
metadata:
  name: load-job
spec:
  template:
    metadata:
      name: load-job
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-job
          image: httpd:latest
          command:
            - sh
            - "-c"
            - |
              while true
              do
              ab -n 20 -c 5 -H "Host: otus-hw.test" http://nginx-nginx-ingress-controller:80/otusapp/users
              sleep 3
              done
  backoffLimit: 3