apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "service-chart.fullname" . }}
  labels:
    {{- include "service-chart.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "service-chart.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "service-chart.selectorLabels" . | nindent 8 }}

    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: HW_HTTP_BIND_PORT
              valueFrom:
                configMapKeyRef:
                  key: HW_HTTP_BIND_PORT
                  name: app-config
            - name: HW_DBSN
              valueFrom:
                secretKeyRef:
                  key: HW_DBSN
                  name: app-secret

          readinessProbe:
            httpGet:
              path: /health/check
              port: 8000
            initialDelaySeconds: 4
            periodSeconds: 3
