replicaCount: 1

image:
  repository: fanyshu/otus-cache-hw

service:
  type: ClusterIP
  port: 8000

metrics:
  serviceMonitor:
    enabled: true

prometheus:
  enabled: true
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}

postgresql:
  enabled: true
  postgresqlUsername: "postgres"
  postgresqlPassword: "password"
  postgresqlDatabase: "postgres_homework"
  service:
    port: "5432"

redis:
  enabled: true
  usePassword: false
  cluster:
    enabled: false
