apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  HW_3_DBSN: aG9zdD1wb3N0Z3JlcyBwb3J0PTU0MzIgdXNlcj1wb3N0Z3JlcyBwYXNzd29yZD1wYXNzd29yZCBkYm5hbWU9cG9zdGdyZXNfaG9tZXdvcmtfMyBzc2xtb2RlPWRpc2FibGUgY29ubmVjdF90aW1lb3V0PTUgYmluYXJ5X3BhcmFtZXRlcnM9eWVz
  POSTGRES_PASSWORD: cGFzc3dvcmQ=