apiVersion: batch/v1
kind: Job
metadata:
  name: init-db
spec:
  template:
    metadata:
      name: init-db
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-job
          env:
            - name: DB_HOST
              value: "postgresql://postgres/postgres_homework_3?user=postgres&password=password"
          image: postgres:latest
          command:
            - sh
            - "-c"
            - |
              psql $DB_HOST <<'EOF'
                create table users (
                    email text primary key,
                    password_hash text not null,
                    first_name text default '',
                    last_name text default ''
                );
              EOF
  backoffLimit: 2