version: "3"
services:
  homework_db:
    image: postgres:latest
    tty: true
    container_name: homework_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres_homework